### ISSUE TITLE
Remove hard coded string literals from Thymeleaf template files

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/crx#101]
Create an interface which should hold all the constants used in the project. 
Refer to that constant file and values in the thymeleaf template file

**References**

[Accessing static constant values from Thymeleaf templates.
Raw
](https://gist.github.com/baybatu/06ac9d3ab2ccc3af0532e42320fd0633)

[Spring MVC part IV: ThymeLeaf advanced usage](https://doanduyhai.wordpress.com/2012/04/14/spring-mvc-part-iv-thymeleaf-advanced-usage/)

**Comment by Rajiv-mar121** [comment]
Constants like.?  Most of things we are loading from sql files. ?

**Comment by kdhrubo** [comment]
[https://github.com/kdhrubo/crx/blob/develop/crm/src/main/resources/templates/fragments/defaultform.html](url)

```
<h5 class="card-title float-xs-left" th:text="${formMeta?.titleNew}"
				th:if="${'**_NEW_**' == formMode}"></h5>
```
So NEW here is a constant. So we need to move this to a constant String in Java interface and reference that in this template html file. 

String FORM_MODE_NEW = "NEW"

and then rewrite this line as

``th:if="${T(com.effectiv.crm.util.Constants).FORM_MODE_NEW == formMode }"`
`

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,
Implemented this feature please review.
#101
Branch: 101_constant_impl
