### ISSUE TITLE
Associate a contact with a vendor

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/crx#243]
Use selects a contact and associates with a vendor.

**Comment by Rajiv-mar121** [comment]
Code pushed.
Branch: feature/243_vendor_contact
Still need to add entries in sql file

**Comment by Rajiv-mar121** [comment]
Code pushed.
Branch: feature/243_vendor_contact_1
Added entries in sql file.

**Comment by Rajiv-mar121** [comment]
Issue already fixed closing it now
