### ISSUE TITLE
Add document to case

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/crx#348]

**Comment by Rajiv-mar121** [comment]
Document is already added to case . but unable to add any new addition to document .

**Comment by Rajiv-mar121** [comment]
Listing is also working now. No issue found.

**Comment by Rajiv-mar121** [comment]
![image](https://user-images.githubusercontent.com/20912676/32626097-5b3c7fbc-c5b4-11e7-8e12-d4679086186a.png)

**Comment by Rajiv-mar121** [comment]
Screen Shot attached.
