### ISSUE TITLE
Convert lead to prospect/opportunity

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/crx#47]

**Comment by kdhrubo** [comment]
Once a Lead is qualified and determined to be a potential sale, the Lead can be converted to an Opportunity. A Contact record and Account record will be created simultaneously to store the personal information and company information.

Opportunity and Contact records creation are mandatory.
Account is optional

Also, other information of the lead for example - emails, documents can be copied/attached to either contact or account.

Do not delete the lead record, but keep it linked to opportunity for future traceability.

When the user clicks on convert button on the lead screen (a new button has to be configured) , then the user is taken to convert lead to opportunity page.

The field mappings are in a separate document.

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,

For issue 47. Is there any reference available which I can follow ?

**Comment by Rajiv-mar121** [comment]
Here as I understand we have to add one button in lead page ?

**Comment by kdhrubo** [comment]
Yes that's correct.
Also a converted boolean field should be introduced in the lead entity if not already done.
That should be set to true. 
You cannot convert 1 lead twice, so the first check in conversion will be to check if this lead has been already converted to opportunity etc.

**Comment by Rajiv-mar121** [comment]
We have to add button in lead details page.

**Comment by kdhrubo** [comment]
Yes

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,

How to pass Opportunity , Account and Contact object in parameter ?

on clicking convert button we have to open oppoutunity form ...with value mapped from lead ?

Regards,
Rajiv

**Comment by kdhrubo** [comment]
Push code to check and review.

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,

On passing defaultform in sql then only form is getting loaded on click of convert button .
"convert?rewrite&form=defaultform"

Now in mapping file I can see "Company " , "Description" and "Lead Source" is only mapped to Oppurtunity.

So how many field need to be added in this form ? Only 3 fields ?
https://docs.google.com/document/d/1eb5pv6uJFMRkknJeZzoDjC_quIJetE7_33MQxJckcRY/edit?ts=58dd2763

Code Pushed please review once.
#47
Branch: 47_lead_to_opportunity

Regards,
Rajiv

**Comment by kdhrubo** [comment]
There is a problem in the configuration. It is actually pointing to the /lead/save URL. So that has to be fixed.
`INSERT INTO form(id,action,method,name,title_new, title_edit, title_detail) VALUES (26,'convertcomplete','post','defaultform','Create New ConverLead', 'Edit ConverLead', 'Account Details');
`
Now you can take each attribute individually instead of an object. In other words change the signature of the convertComplete method to remove opportunity and work with only the fields in the request parameter like contact firstName, lastName etc.

Then inside controller create the objects. Do not save them individually, JPA should cascade the save in 1 transaction in the business delegate.

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,

Can we discuss over call about this ?

I have several question against this requirements.

Regards,
Rajiv

On Tue, Apr 11, 2017 at 8:57 PM, Dhrubojyoti Kayal <notifications@github.com
