### ISSUE TITLE
Show recycle bin

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/crx#53]
Recycle bin shows entities that are deleted but not yet purged

**Comment by kdhrubo** [comment]
`AbstractBaseController`

Add 2 new methods similar to
```
@RequestMapping("/list")
	public ModelAndView list(@RequestParam(value="listView", required=false) String listView) {
```
And

```
@RequestMapping("/list/data")
	public @ResponseBody DatatablesResponse<T> list(@DatatablesParams  DatatablesRequest request) {
```

The request mappings to be changed as follows

`@RequestMapping("/recycle")`

and

`@RequestMapping("/recycle/data")

Change the method names to 
`recyleBinList`

In the second method where data is actually retrieved from DB, change the following line

`List<T> dataList = service.findAllByDeleted(false);`

to

`List<T> dataList = service.findAllByDeleted(true);

This will retrieve all the records which have been deleted for that entity.
`

`

**Comment by kdhrubo** [comment]
To make this viewable on GUI.

1> Configure menu item for all entities
2> Configure the UI view mapping for this URL.
3> Also configure the list page. The buttons can be as is.

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,

In new method "recyleBinList"
We no need to change any content in this method ?

for UI mapping .. we have to create new .sql file ?

Regards,
Rajiv

**Comment by kdhrubo** [comment]
I think it should retrieve the details about the recyle list.

UI mapping - please use the existing file for each entity.

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo
I have to make modification in all entity --> Lead,prospect. account and contact..?
for recycle feature ?
All corresponding files need to be modified ?
As Example..
INSERT INTO ui_view_definition (name,req_url,layout,title) VALUES ('defaultlist','/lead/list','layouts/default','Leads');
INSERT INTO ui_view_definition (name,req_url,layout,title) VALUES ('defaultlist','/lead/recycle','layouts/default','Leads');


Regards,
Rajiv

**Comment by kdhrubo** [comment]
Yes, recycle bin applicable for Lead, Prospect, Account and Contact.

**Comment by Rajiv-mar121** [comment]
I am getting confused in sql entry.
How to see this effect on gui ?

Regards,
Rajiv

On Sun, Jan 22, 2017 at 9:52 PM, Dhrubojyoti Kayal <notifications@github.com

**Comment by kdhrubo** [comment]
To browse to the UI screen you need a menu item entry for the module. For example for Lead add this entry.
`
INSERT INTO menu_item (name,href,icon,label,module_id) VALUES ('recyleLeads', '/lead/recycle', 'fa fa-plane', 'Recycle Bin',1);`

Then I am able to see the link and browse to the recycle bin page for Lead. This should be added for other modules - Prospect, Contact, Account. 

Also noticed an issue on in the recyleBinList page. 

`List<T> dataList = service.findAllByDeleted(**false**);

This should be **true**. Because we want to get all those entries which are deleted or delete = true.

`

**Comment by kdhrubo** [comment]
I have pushed the small change of SQL entry in this branch.

**Comment by Rajiv-mar121** [comment]
Ok Dhrubo,

Thanks I will check it.

Rajiv

On Mon, Jan 23, 2017 at 1:42 AM, Dhrubojyoti Kayal <notifications@github.com

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,

Now "recycle bin" is visible in GUI but I noticed that it is listing all active records deleted=false not deleted=true.

INSERT INTO data_table(id,name,pagination,server_url,title) VALUES (1,'listLead', true, '/lead/list/data','Lead List');
here ID is primary key hence we cant insert "/lead/recycle/data" in data_table..
that y it is not pointing to our new method
/recycle/data.
it is hitting older method.

Regards,
Rajiv

**Comment by Rajiv-mar121** [comment]
Can't we use same existing method and pass a parameter on click of "recycle bin" and accordingly we will put a check which record need to be populated.

Regards,
Rajiv

**Comment by kdhrubo** [comment]
Yes we can do that.

**Comment by kdhrubo** [comment]
@Rajiv-mar121 
Recycle bin working for Lead. Closing this issue. 
We will open recycle bin issues for other entities separately. Now it is a matter of configuration.
