### ISSUE TITLE
Purge from recycle bin

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/crx#54]

**Comment by kdhrubo** [comment]
1> The method used for details for an entity in the AbstractController to be reused.
2> Check if this is a recycle in the request URL string. 
3> If recycle is present set a new model view variable - recyle=true
4> In the UI if this parameter is present and set to true show a button in the details page button bar with title 'Purge' in red background (bootstrap error)
5> When the user clicks on this button the result is permanently deleted from database. 
So no record for this entity will exist in any of the db tables for that particular entity.

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,
1) Following method need to be modified correct me if I am wrong ?
@RequestMapping({"/details", "/edit"})
	public ModelAndView details(@RequestParam("id") ID id,@RequestParam(name="form",required=false) String formName){

2) As per my understanding I have to add new @RequestParam(name="url") and I have to check whether recycle string is present or not ?

Regards,
Rajiv

**Comment by kdhrubo** [comment]
1>Yes that method needs to be modified and I have already made that tiny change now as part of another issue

```
if(!ServletUtil.isRecycleRequest()) {
			listViewNameDerived = StringUtil.isBlank(listView) ? "list" + getGenericTypeClass().getSimpleName() : listView;
		}
		else{
			listViewNameDerived = "recycleList" + getGenericTypeClass().getSimpleName(); 
			**mv.addObject(RECYCLE, true);**
		}
```

2> You do not need any request parameter as the ServletUtil.isRecycleRequest() is capable of checking the current request URL.

Now the change is required in the UI. If "recycle" is set and set to true, then you know you are viewing a record which is deleted and in present in recyle bin. So now you can show the special "Purge" button.

Lets make that UI change as first step.

Then we can implement the logic for the "Purge" button click. That method can also be in the abstract base controller to be available to all the entities. When a user clicks on Purge that record is deleted from DB.In other words its a hard delete. If the delete is successful, the user is taken back to the recycle bin page.

**Comment by Rajiv-mar121** [comment]
Ok Dhrubo..
Means I have to add purge button . but currently delete button is also being displayed ..
Do I need to add extra one purge button..

**Comment by kdhrubo** [comment]
@Rajiv-mar121 
Only restore and purge button should be shown for entities in recycle bin when the detailed page is shown. You will not be able to edit this entity either. 

Refer to the gist 
[[https://gist.github.com/kdhrubo/42ff0fb582dba1a06ec9cae94f61d1fe]](https://gist.github.com/kdhrubo/42ff0fb582dba1a06ec9cae94f61d1fe)

**Comment by Rajiv-mar121** [comment]
I dont see any button.html file 
in workspace.
Same snippet is present in defaultform.html and defaultlist.html

**Comment by kdhrubo** [comment]
[https://gist.github.com/kdhrubo/20b4faebbe4983a408dc6aabb9ad2f8e](https://gist.github.com/kdhrubo/20b4faebbe4983a408dc6aabb9ad2f8e)

**Comment by kdhrubo** [comment]
@Rajiv-mar121 

1> Now in the abstract base controller add a method - purge. The request URL will be /purge so add request mapping accordingly. The only parameter to this method will be the id field as request param. Check the delete method for example in the same class

2> Add the same method in the service. The service method accepts the id. This should call the repository.delete method with id. 

Check that the data / record row is REMOVED out from DB.

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,

Added purge also
Please review the and merge it accordingly.
Branch: 54_purge_records
