### ISSUE TITLE
Restore from recycle bin

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/crx#55]

**Comment by kdhrubo** [comment]
@Rajiv-mar121 

1> Now in the abstract base controller add a method - restore. The request URL will be /restore so add request mapping accordingly. The only parameter to this method will be the id field as request param. Check the delete method for example in the same class

2> Add the same method in the service. The service method accepts the id. This should be exactly same as the delete method. But in this case we have to restore from recycle bin. So the deleted flag needs to be reversed or set to false. 

Check that the data / record row is NOT showing in recycle bin.
The data/record row should show up under normal list.

**Comment by Rajiv-mar121** [comment]
It is completed.
Branch: 54_purge_records
