### ISSUE TITLE
Prospect CRUD

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/crx#6]
1> Add Prospect form configuration
2> Add Prospect list configuration
3> Add Prospect repository Java class
4> Add Prospect service Java class
5> Add Prospect controller Java class

**Comment by Rajiv-mar121** [comment]
Assigned to myself.

**Comment by Rajiv-mar121** [comment]
Code pushed to "feature/6_prospect_service_controller"

**Comment by Rajiv-mar121** [comment]
Added prospect entries in sql files.

**Comment by Rajiv-mar121** [comment]
feature/6_prospect_sql

**Comment by Rajiv-mar121** [comment]
Code pushed. Please review
Branch : feature/6_prospect_sql_1

**Comment by Rajiv-mar121** [comment]
Code pushed. Corrected sql sequence.
6_prospect_sql_fields

**Comment by kdhrubo** [comment]
Code completed.
