### ISSUE TITLE
List events associated with lead

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/crx#76]

**Comment by kdhrubo** [comment]
@Rajiv-mar121 

Event is some meeting, webinar etc associated with a lead. This is an entity which is associated with Lead. Event will be created as a sub module. For example Task is an association for some work that needs to be done by a due date. This is also a sub module. 

The Effectiv Application Framework takes care of sub module. Steps to create a sub module are below

1> Create the entity LeadEvent. The attributes are exactly same as LeadTask.

2> Create the LeadEventRepository (refer to lead task repository)

3> Create the LeadEventService (refer to lead task service)

4> Crete the LeadEventController (refer to the lead task controller). The base request mapping URL should be '/lead/event'

5> Create the sub module configuration using SQL follow exactly as the data-submodule-lead-task.sql file. This file can be named as data-submodule-lead-event.sql.

Then you should see the Event drop down appearing in lead details page (not in recycle lead details page). From there click on list events page and it should show only the events associated for that particular lead (currently there is a bug that will be fixed tomorrow). You can create a new event using the new link. Ensure in the DB the lead id is saved correctly.

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,

LeadEvent is a groovy file ?like LeadTask.groovy ?
File "data-submodule-lead-event.sql" is already present in branch.

Regards,
Rajiv

**Comment by Rajiv-mar121** [comment]
Hi Dhrubo,

I got answers of my question posted above.

Rajiv
